# Site settings
title: The personal website/portfolio of Peter Cowal
email: pcowal at gmail dot com
description: "Built with Jekyll"
baseurl: ""
url: "http://petercowal.github.io"
github_username:  petercowal

# Build settings
markdown: kramdown
permalink: pretty
